{
 "title": "TOF_metric",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "hEvtChan0",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grams_tof",
     "rawSql": "SELECT \n  bin_index AS \"Channel\", \n  bin_content AS \"Event rate\"\nFROM tof_monitor\nWHERE hname = 'hEvtChan0'\nAND timestamp = (SELECT MAX(timestamp) FROM tof_monitor WHERE hname = 'hEvtChan0')\nORDER BY bin_index;"
    }
   ]
  },
  {
   "title": "hEvtTime0",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "grams_tof",
     "rawSql": "SELECT \n  bin_index AS \"CPU time\", \n  bin_content AS \"Event rate\"\nFROM tof_monitor\nWHERE hname = 'hEvtTime0'\nAND timestamp = (SELECT MAX(timestamp) FROM tof_monitor WHERE hname = 'hEvtTime0')\nORDER BY bin_index;"
    }
   ]
  },
  {
   "title": "hEvtChan1",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "grams_tof",
     "rawSql": "SELECT \n  bin_index AS \"Channel\", \n  bin_content AS \"Event rate\"\nFROM tof_monitor\nWHERE hname = 'hEvtChan1'\nAND timestamp = (SELECT MAX(timestamp) FROM tof_monitor WHERE hname = 'hEvtChan1')\nORDER BY bin_index;"
    }
   ]
  },
  {
   "title": "hEvtTime1",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "grams_tof",
     "rawSql": "SELECT \n  bin_index AS \"CPU time\", \n  bin_content AS \"Event rate\"\nFROM tof_monitor\nWHERE hname = 'hEvtTime1'\nAND timestamp = (SELECT MAX(timestamp) FROM tof_monitor WHERE hname = 'hEvtTime1')\nORDER BY bin_index;"
    }
   ]
  }
 ]
}